# Generated by Django 4.2.5 on 2025-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_links_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubelink",
            name="created_at",
        ),
        migrations.AddField(
            model_name="youtubelink",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubelink",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="youtubelink",
            name="url",
            field=models.URLField(),
        ),
    ]
