# Generated by Django 4.2.5 on 2025-04-01 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_links_api", "0003_comment_category_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
    ]
