# Generated by Django 4.2.5 on 2025-04-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("youtube_links_api", "0006_rename_user_id_youtubelink_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="youtube_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="youtube_links_api.youtubelink",
            ),
        ),
    ]
